// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.hsbc.service;

public final class EmpServiceImpl_Stub
    extends java.rmi.server.RemoteStub
    implements com.hsbc.service.IEmpService
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getEmployee_0;
    
    static {
	try {
	    $method_getEmployee_0 = com.hsbc.service.IEmpService.class.getMethod("getEmployee", new java.lang.Class[] {int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public EmpServiceImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getEmployee(int)
    public com.hsbc.entity.Emp getEmployee(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getEmployee_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -7704830096245454556L);
	    return ((com.hsbc.entity.Emp) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
