// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.hsbc.service;

public final class calcServiceImpl_Stub
    extends java.rmi.server.RemoteStub
    implements com.hsbc.service.IcalcService, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_SI_0;
    
    static {
	try {
	    $method_SI_0 = com.hsbc.service.IcalcService.class.getMethod("SI", new java.lang.Class[] {int.class, int.class, int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public calcServiceImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of SI(int, int, int)
    public double SI(int $param_int_1, int $param_int_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_SI_0, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Integer($param_int_2), new java.lang.Integer($param_int_3)}, 1998538440647528461L);
	    return ((java.lang.Double) $result).doubleValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
