// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.hsbc.service;

public final class CalcServiceImpl_Stub
    extends java.rmi.server.RemoteStub
    implements com.hsbc.service.ICalcService, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_calcInterest_0;
    
    static {
	try {
	    $method_calcInterest_0 = com.hsbc.service.ICalcService.class.getMethod("calcInterest", new java.lang.Class[] {int.class, float.class, int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public CalcServiceImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of calcInterest(int, float, int)
    public double calcInterest(int $param_int_1, float $param_float_2, int $param_int_3)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_calcInterest_0, new java.lang.Object[] {new java.lang.Integer($param_int_1), new java.lang.Float($param_float_2), new java.lang.Integer($param_int_3)}, -2015193939830568714L);
	    return ((java.lang.Double) $result).doubleValue();
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
